import type { Metadata } from "next";
import "../styles/globals.css";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Sidebar />
        </main>
        {children}
        <Footer />
      </body>
    </html>
  );
}
