import type { Metadata } from "next";
import "../styles/globals.css";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Inspetron",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex">
          <Sidebar />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
